export const transactionsViewOptions = ["Yearly", "Monthly", "Daily"];
export const types = ["Credit", "Debit"];
export const categories = [
  "Grocery",
  "Household",
  "Entertainment",
  "Internet",
  "Car",
  "Electricity",
];

export const banksOptions = [
  "Access Bank",
  "First Bank of Nigeria",
  "Zenith Bank",
  "Guaranty Trust Bank (GTBank)",
  "United Bank for Africa (UBA)",
  "Ecobank Nigeria",
  "Stanbic IBTC Bank",
  "Union Bank of Nigeria",
  "Fidelity Bank Nigeria",
  "Sterling Bank",
  "First City Monument Bank (FCMB)",
  "Polaris Bank",
  "Wema Bank",
  "Heritage Bank",
  "Keystone Bank",
  "Unity Bank",
  "Jaiz Bank",
  "SunTrust Bank",
  "Providus Bank",
  "Coronation Merchant Bank",
  "Titan Trust Bank",
  "Standard Chartered Bank",
  "CitiBank Nigeria",
  "Stanbic IBTC Pension Managers",
  "FSDH Merchant Bank",
  "Union Homes Savings and Loans",
  "SunTrust Mortgage Bank",
  "TrustBank",
  "Covenant Microfinance Bank",
  "Globus Bank",
  "AB Microfinance Bank",
  "Bank of Agriculture",
  "NPF Microfinance Bank",
  "Citi Trust Financial Services",
  "Rand Merchant Bank",
  "Taj Bank Limited",
  "TagPay",
  "Fortis Microfinance Bank",
  "Sparkle",
  "OneFi",
  "JubileeLife Mortgage Bank",
  "ABSA Bank Nigeria",
  "First Alliance Pension and Benefits",
  "Specta",
  "Page Financials",
  "Imperial Homes Mortgage Bank",
  "Sterling Mortgage Bank",
  "FBNQuest Merchant Bank",
  "Kuda Bank",
  "Glocal Payments",
  "Covenant Capital Plc",
  "Lagos Building Investment Company",
  "i-OneC",
  "FBN Mortgages",
  "Diamondbank",
  "Keystone Mortgage Bank",
  "Parkway Mortgage Bank",
  "Monetaria Finance",
  "FBN General Insurance",
  "Fortis Mobile Money",
  "GBC Professional Services",
  "Accion Microfinance Bank",
  "FBNInsurance",
  "VFD Microfinance Bank",
  "Progressive Microfinance Bank",
  "Nigeria Mortgage Refinance Company (NMRC)",
  "Mainstreet Bank",
  "Agribank",
  "Equatorial Trust Bank (ETB)",
  "ProvidusBank",
  "Edge Certified Trustees",
  "Afribank Nigeria",
  "Wetlands Microfinance Bank",
  "Fortis Microfinance Bank",
  "Credent Investment Managers",
  "Anchor Insurance Company",
  "GSL Trustees Limited",
  "NPF Pensions Limited",
  "Lagos Building Investment Company",
  "First Funds Limited",
  "PTL Trustees",
  "NPF Microfinance Bank",
  "FirstPension Custodian",
  "NOVA Merchant Bank",
  "Sterling Assurance Nigeria",
  "SCC Assurance Plc",
  "CrusaderSterling Pensions",
  "Leadway Assurance",
  "Capstone Microfinance Bank",
  "Gateway Mortgage Bank",
  "Ndiorah Direct",
  "FBN Capital",
  "Omoluabi Mortgage Bank",
  "Stanbic IBTC Pension Managers",
  "Radix Pension Managers",
  "Apel Asset",
  "Yardvest Nigeria Limited",
  "Venture Capital Management Limited",
  "Stanbic IBTC Stockbrokers",
  "Meristem Wealth Management",
  "Zenith Securities Limited",
  "FBN Mortgages",
  "Stanbic IBTC Asset Management",
  "Chapel Hill Denham Management",
  "FBNQuest Trustees",
  "FCMB Pensions",
  "New Prudential Mortgage Bank",
  "VFD Group",
  "Asset and Resource Management Company (ARM)",
  "Etranzact",
  "Primero Africa Securities",
  "FBNQuest Capital",
  "Cowry Asset Management",
  "United Capital Asset Management",
  "Coronation Securities",
  "SCAON Trustees",
  "Investment One Financial Services",
  "Cytonn Investment",
  "Stanbic IBTC Trustees",
  "Stanbic IBTC Bank (SWIFTPayroll)",
  "Everdon Bureau de Change",
  "Wema Asset Management",
  "IBTC Pension Managers",
  "Assurance Financial Planners",
  "APT Pension Funds Managers",
  "SFS Capital Nigeria",
  "Financial Derivatives Company",
  "Fintrak Software",
  "Ibile Holdings",
  "Valucard Nigeria",
  "Metro Capital",
  "Phoenix Capital",
  "Purple Money",
  "Trustfund Pensions",
  "Emerald Trust",
  "Pay Attitude Online",
  "FSDH Asset Management",
  "Global Accelerex",
  "Zedvance",
  "Meristem Registrars",
  "EFG Hermes",
  "Greenwich Trust Limited",
  "Orient Global Manufacturing Limited",
  "Meristem Trustees",
  "Merit Advisory Partners",
  "Infiniti Trust Limited",
  "FBN General Insurance",
  "Great Nigeria Insurance",
  "Heirs Life Assurance",
  "Goldlink Insurance",
  "Ibile Oil and Gas Corporation",
  "Ibile Holdings",
  "i-Financial Services",
  "ICSL",
  "Securities and Exchange Commission (SEC Nigeria)",
  "Nigerian Investment Promotion Commission (NIPC)",
  "National Insurance Commission (NAICOM)",
  "Pension Transitional Arrangement Directorate (PTAD)",
  "Nigeria Mortgage Refinance Company (NMRC)",
  "African Reinsurance Corporation",
  "Staco Insurance",
  "African Finance Corporation",
  "FSDH Merchant Bank",
  "NSIA Insurance",
  "Lasaco Assurance",
  "CSCS",
  "STACO Insurance",
  "LASACO Pension",
  "Himma International Finance",
  "Forte Oil",
  "Honeywell Flour Mills",
  "Nigerian Breweries",
  "Guinness Nigeria",
  "Zenith Registrars",
  "GlaxoSmithKline Nigeria",
  "Nigerian Aviation Handling Company",
  "UBA Registrars",
  "Fidson Healthcare",
  "Flour Mills of Nigeria",
  "May & Baker Nigeria",
  "NASCON Allied Industries",
  "Transcorp Registrars",
  "Red Star Express",
  "Nigerian Enamelware",
  "International Breweries",
  "Tripple Gee and Company",
  "United Capital Registrars",
  "Okomu Oil Palm Company",
  "Julius Berger Nigeria",
  "CAP Plc",
  "Berger Paints",
  "Linkage Assurance",
  "Japaul Gold and Ventures",
  "Guinea Insurance",
  "Neimeth International Pharmaceuticals",
  "Prestige Assurance",
  "Nigerian Ropes",
  "DN Tyre & Rubber",
  "SCOA Nigeria",
  "Fidson Healthcare",
  "Trans-Nationwide Express",
  "PZ Cussons Nigeria",
  "Costain West Africa",
  "Thomas Wyatt Nigeria",
  "Flour Mills of Nigeria",
  "MRS Oil Nigeria",
  "Oando",
  "Unile",
];
